"use client";

import { useCallback } from "react";
import { toast } from "sonner";
import type { AiPreset } from "@/data";
import { stripFrontMatter } from "@/domain/source/frontmatter";
import { useServices } from "@/app-shell/services";
import { useEngine } from "@/engine/provider";
import { useDeckActions } from "@/hooks/use-deck-actions";
import { useFileActions } from "@/hooks/use-file-actions";
import { useAi } from "@/stores/ai";
import { useUi } from "@/stores/ui";
import { useWorkspace } from "@/stores/workspace";

export const AI_STEPS = ["Reading llms.txt syntax guide", "Planning the outline", "Writing slides", "Choosing theme & motion", "Validating syntax"];

const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));
/** Drives the AI dialog: request → "typing" reveal → Wasm validation → apply. */
export function useAiGenerate() {
  const { ai } = useServices();
  const engine = useEngine();
  const deck = useDeckActions();
  const files = useFileActions();

  const generate = useCallback(
    async (preset?: AiPreset) => {
      const st = useAi.getState();
      const prompt = preset ? preset.prompt : st.prompt.trim();
      if (!prompt) return st.set({ error: "Describe the deck first, or pick an example." });
      const run = st.runId + 1;
      const alive = () => useAi.getState().runId === run;
      st.set({ runId: run, phase: "busy", step: 0, error: "", prompt, typed: "" });
      await wait(500);
      if (!alive()) return;
      useAi.getState().set({ step: 1 });
      let draft;
      try {
        draft = await ai.generate(prompt, { slides: st.count });
      } catch (e) {
        if (!alive()) return;
        return useAi.getState().set({ phase: "idle", error: (e as Error).message });
      }
      if (!alive()) return;
      const md = draft.markdown.trim() + "\n";
      useAi.getState().set({ step: 2, error: "" });
      const chunk = Math.max(24, Math.ceil(md.length / 40));
      for (let i = 0; i <= md.length; i += chunk) {
        if (!alive()) return;
        useAi.getState().set({ typed: md.slice(Math.max(0, i - 600), i) });
        await wait(30);
      }
      useAi.getState().set({ step: 3 });
      await wait(400);
      const parsed = engine.parse(md);
      const errs = parsed.problems.filter((p) => p.sev === "error").length;
      useAi.getState().set({ step: 4 });
      await wait(350);
      if (!alive()) return;
      const summary = `${parsed.slides.length} slides · ${errs ? `${errs} syntax error(s) — check Problems` : "valid syntax"} · generated by ${draft.provider}${draft.model ? ` · ${draft.model}` : ""}`;
      useAi.getState().set({ phase: "done", markdown: md, summary, seed: useAi.getState().seed + 1 });
    },
    [ai, engine],
  );

  const apply = useCallback(() => {
    const { markdown, target } = useAi.getState();
    const close = () => useUi.getState().closeModal();
    if (target === "insert") {
      deck.appendSlides(stripFrontMatter(markdown));
      close();
      return toast("Added AI slides to the end of this deck");
    }
    if (target === "replace") {
      useWorkspace.getState().setSource(markdown);
      close();
      return toast("Replaced deck with AI draft — the commit dialog shows the diff");
    }
    const meta = engine.parse(markdown).meta;
    const id = (meta.title || "ai-deck").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "ai-deck";
    const look: Record<string, string> = { ...meta };
    delete look.title;
    files.createFromTemplate({ id, name: meta.title || "AI deck", look, md: stripFrontMatter(markdown).trim() });
    close();
  }, [deck, files, engine]);

  const cancel = () => useAi.getState().set({ runId: useAi.getState().runId + 1, phase: "idle" });
  return { generate, apply, cancel };
}
