#!/usr/bin/env node
/**
 * Landing page assets from src/features/landing/showcase.md:
 *   src/features/landing/demo-link.ts  share-link hash for the "View a demo deck" button
 *   public/landing/slide-N.jpg         real rendered slides used as 3D panel textures
 * Needs a running app (default http://localhost:3100) and Playwright. Outputs are committed.
 * Usage: node scripts/landing-assets.mjs [baseUrl]
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";
import { deflateRawSync } from "node:zlib";
import { root } from "./ui-bundle.mjs";

const base = process.argv[2] ?? "http://localhost:3100";
const md = readFileSync(join(root, "src/features/landing/showcase.md"), "utf8");

// Same format as src/domain/share/codec.ts: [version 1][flags 0] + deflate-raw(JSON), base64url.
const payload = { v: 1, md, path: "showcase.md", name: "md2slides showcase", created: Date.UTC(2026, 8, 26), opts: { notes: false, download: true, present: false } };
const bytes = Buffer.concat([Buffer.from([1, 0]), deflateRawSync(Buffer.from(JSON.stringify(payload)))]);
const hash = bytes.toString("base64url");
writeFileSync(
  join(root, "src/features/landing/demo-link.ts"),
  `// Generated by scripts/landing-assets.mjs from showcase.md — do not edit.\nexport const DEMO_DECK_HASH = "${hash}";\n`,
);

const require = createRequire(import.meta.url);
const { chromium } = (() => {
  for (const id of ["playwright", "/opt/node22/lib/node_modules/playwright"]) {
    try {
      return require(id);
    } catch {}
  }
  throw new Error("Playwright not found: npm i -D playwright");
})();
const out = join(root, "public/landing");
mkdirSync(out, { recursive: true });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 }, deviceScaleFactor: 2 });
await page.goto(`${base}/v#${hash}`);
await page.waitForSelector("main section");
await page.waitForTimeout(2500);
const slides = page.locator("main section [style*='aspect-ratio']");
const n = await slides.count();
for (let i = 0; i < n; i++) {
  await slides.nth(i).scrollIntoViewIfNeeded();
  await page.waitForTimeout(300);
  await slides.nth(i).screenshot({ path: join(out, `slide-${i + 1}.jpg`), type: "jpeg", quality: 82 });
}
await browser.close();
console.log(`Wrote demo link and ${n} slide textures.`);
